/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { FileUploader } from "./index"

// @ts-ignore
export function indexTemplateHtml(this: FileUploader) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{on:{"drop":function($event){return _vm.onDrop($event)},"paste":function($event){return _vm.onPaste($event)}}},[_vm._l((_vm.requests),function(request,i){return _c('div',{key:i,staticClass:"file-uploader-progress",attrs:{"title":request.file.name}},[_c('div',{style:(_vm.getProgressWidth(request))},[_vm._v(_vm._s(request.percent)+"%")])])}),_vm._v(" "),_c('p',{staticClass:"file-uploader-container"},[_vm._v("\n        "+_vm._s(_vm.localeObject.dragAndDrop)+"\n        "),_c('span',[_vm._v(_vm._s(_vm.localeObject.selectFile))]),_vm._v("\n        "+_vm._s(_vm.localeObject.pasteFromClipboard)+"\n        "),_c('input',{attrs:{"type":"file","multiple":_vm.multiple,"accept":_vm.accept},on:{"change":function($event){return _vm.onFileUploaded($event)}}})])],2)}
// @ts-ignore
export var indexTemplateHtmlStatic = [  ]
// tslint:enable
