// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createBlock as _createBlock, createTextVNode as _createTextVNode, createVNode as _createVNode, Fragment as _Fragment, openBlock as _openBlock, renderList as _renderList, toDisplayString as _toDisplayString } from 'vue'
// tslint:disable
/* eslint-disable */

export function indexTemplateHtml(_ctx, _cache) {
  return (_openBlock(), _createBlock("div", {
    onDrop: _cache[2] || (_cache[2] = $event => (_ctx.onDrop($event))),
    onPaste: _cache[3] || (_cache[3] = $event => (_ctx.onPaste($event)))
  }, [
    (_openBlock(true), _createBlock(_Fragment, null, _renderList(_ctx.requests, (request, i) => {
      return (_openBlock(), _createBlock("div", {
        key: i,
        class: "file-uploader-progress",
        title: request.file.name
      }, [
        _createVNode("div", {
          style: _ctx.getProgressWidth(request)
        }, _toDisplayString(request.percent) + "%", 5 /* TEXT, STYLE */)
      ], 8 /* PROPS */, ["title"]))
    }), 128 /* KEYED_FRAGMENT */)),
    _createVNode("p", { class: "file-uploader-container" }, [
      _createTextVNode(_toDisplayString(_ctx.localeObject.dragAndDrop) + " ", 1 /* TEXT */),
      _createVNode("span", null, _toDisplayString(_ctx.localeObject.selectFile), 1 /* TEXT */),
      _createTextVNode(" " + _toDisplayString(_ctx.localeObject.pasteFromClipboard) + " ", 1 /* TEXT */),
      _createVNode("input", {
        type: "file",
        multiple: _ctx.multiple,
        accept: _ctx.accept,
        onChange: _cache[1] || (_cache[1] = $event => (_ctx.onFileUploaded($event)))
      }, null, 40 /* PROPS, HYDRATE_EVENTS */, ["multiple", "accept"])
    ])
  ], 32 /* HYDRATE_EVENTS */))
}
/* eslint-enable */
// tslint:enable
