/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
export const vueTemplateHtml = `<div @drop="onDrop($event)" @paste="onPaste($event)"><div v-for="request in requests" class="file-uploader-progress" :title="request.file.name"><div :style="getProgressWidth(request)">{{request.percent}}%</div></div><p class="file-uploader-container">{{localeObject.dragAndDrop}}<span>{{localeObject.selectFile}}</span>{{localeObject.pasteFromClipboard}} <input type="file" :multiple="multiple" :accept="accept" @change="onFileUploaded($event)"></p></div>`;
